config/routes.rb
Cats::Application.routes.draw do

  match 'home' => 'pages#index'
  root :to => 'pages#index'

  match 'cats/random-number' => 'cats#random_number'
  resources :cats

  match 'home' => 'pages#home'
  resources :pages

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :description, :image, :name, :page_id
  belongs_to :page
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :name

  has_many :cats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # GET /cats
  # GET /cats.json
  def index
    if request.xhr?
      sample_size = (1..5).to_a.sample
      @cats = Cat.find(:all).sample(sample_size)
    else
      @cats = Cat.all
    end
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    @cat = Cat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cat }
    end
  end

  # GET /cats/new
  # GET /cats/new.json
  def new
    @cat = Cat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cat }
    end
  end

  # GET /cats/1/edit
  def edit
    @cat = Cat.find(params[:id])
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(params[:cat])

    @cat.page_id = 1 # hard code this for now

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render json: @cat, status: :created, location: @cat }
      else
        format.html { render action: "new" }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cats/1
  # PUT /cats/1.json
  def update
    @cat = Cat.find(params[:id])

    respond_to do |format|
      if @cat.update_attributes(params[:cat])
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /pages
  # GET /pages.json
  def index
    @page = Page.first #Only one page in DB for now
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cats/_cat.html.haml
.accordion.hidden{:id => "accordion_#{Time.now.to_i}_#{cat_counter}"}
  .accordion-group
    .accordion-heading.cat{"data-time"=>"#{cat.created_at.to_i}"}
      %a{:href => "#collapse_#{Time.now.to_i}_#{cat_counter}", :class => "accordion-toggle", "data-toggle" => "collapse", "data-parent" => "#accordion_#{Time.now.to_i}_#{cat_counter}"}
        #{cat.name}
    .accordion-body.collapse{:id => "collapse_#{Time.now.to_i}_#{cat_counter}"}
      .accordion-inner
        %ul
          %li 
            %i="posted on #{cat.created_at.strftime('%b %d, %Y at %I:%M %p')}" 
          %li 
            %b="Age: #{cat.age}" 
          %li 
            %b="Description: #{cat.description}" 

app/views/cats/_form.html.haml
= form_for @cat, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :age, :class => 'control-label'
    .controls
      = f.number_field :age, :class => 'number_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :image, :class => 'control-label'
    .controls
      = f.text_area :image, :class => 'text_area'
  .control-group
    = f.label :page_id, :class => 'control-label'
    .controls
      = f.number_field :page_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), cats_path, :class => 'btn'

app/views/cats/edit.html.haml
- model_class = Cat
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/cats/index.html.haml
- model_class = Cat
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:age)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:image)
      %th= model_class.human_attribute_name(:page_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @cats.each do |cat|
      %tr
        %td= link_to cat.id, cat_path(cat)
        %td= cat.name
        %td= cat.age
        %td= cat.description
        %td= cat.image
        %td= cat.page_id
        %td=l cat.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_cat_path(cat), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), cat_path(cat), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_cat_path, :class => 'btn btn-primary'

app/views/cats/index.js.erb
<% unless @cats.empty? %>
var temporal_id = <%= Time.now.to_i %>
$(".cats").prepend("<div class='items new-items' id='" + temporal_id + "'><%=raw escape_javascript(render(@cats)) %></div>");

var current_cats = parseInt($("#page h3").text().split(" ")[0],10);
var new_cats = <%= @cats.size %>
current_cats += parseInt(new_cats, 10);
$("#page h3").text(current_cats + "  more cats since you last viewed!");

var current_cats_total = parseInt($("#page h5").text().split(" ")[0],10);
current_cats_total += parseInt(new_cats, 10);
$("#page h5").text(current_cats_total + "  total cats!");


$("#page-title").text(current_cats + " Cats - Real Time Updates");
<% end %>

app/views/cats/new.html.haml
- model_class = Cat
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/cats/show.html.haml
- model_class = Cat
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @cat.name
%p
  %strong= model_class.human_attribute_name(:age) + ':'
  %br
  = @cat.age
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @cat.description
%p
  %strong= model_class.human_attribute_name(:image) + ':'
  %br
  = @cat.image
%p
  %strong= model_class.human_attribute_name(:page_id) + ':'
  %br
  = @cat.page_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), cats_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_cat_path(@cat), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), cat_path(@cat), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title{:id => "page-title"}Cats - Real Time Updates
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags 
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}

:plain
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]--> 
  <script>      
     var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-34944702-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

%body
.container
  .navbar.navbar-fixed-top
    .navbar-inner.nav-space
      .brand
        Cats
      %ul.nav
        %li= link_to "Home Page", root_path
        /%li= link_to "Picture Gallery"
        %li= link_to "Github Source", "https://github.com/xianthe/ballin-octo-pix"
.main-content
  = yield
.container
  .navbar.navbar-fixed-bottom
    .navbar-inner
      %ul.nav
        %li= link_to "List of Cats", cats_path
      .pull-right
        %footer
          %h5 Copyright 2012 Valerie Thompson

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
.container-fluid
  .row-fluid
    .span5
      %header
        %h2 Twitter Real Time Updates Example
        %p This is a sample demonstration  of how Twitter does real time polling of updates. Let as many cats as you want pile up and click "Open New Items" to see them. The "Stop Polling" button will change to a "Start Polling" button so you can get more cats from the server. 

        #page
          -unless @page.cats.empty?
            .alert.alert-info
              %h3==#{pluralize(@page.cats.size, 'cat')} more since you last viewed!
            %h5==#{pluralize(@page.cats.size, 'cat')} total!
          %a{:href=>"#", :onclick => "resetInterval()", :class => "btn dropdown-toggle pull-left", :id => "polling", "data-toggle"=>"dropdown"}
            Stop Polling
          .btn-group.pull-right
            %a{:href=>"#", :onclick => "revealNewItems()", :class => "btn btn-primary"}
              Open New Items
            %a{:href=>"#", :onclick => "revealNewItems()", :class => "btn btn-primary"}
              %span
                %i{:class => "icon-plus icon-white"}
          %br
          %br
          .cats.well.hidden.clearfix
            .items{:class => "new-items"}
              = render (@page.cats)

    .span7
      %h4 Exercise

      .well
        %p== If you haven't already checked out twitter's real-time search, try #{link_to "http://twitter.com/search?q=arenanet", "http://twitter.com/search?q=arenanet"}. If you leave the results on, you'll have real-time updates similar to facebook news feed updates. (i.e. 1,203 more tweets since you started searching will highlight just below the search bar and the total counter in the browser's title bar will update as well).

        %p Create a page that updates the list on the left hand-side, with latest items inserted at the top and highlighted. There should also be text inserted above the currently selected image stating "X more images since you viewed" with the browser title bar updated.

        %p You may use any server technology you'd like (Node.js, ASP.NET MVC, PHP, or perhaps even pulling from a 3rd party API such as Flickr, Photobucket); the server only needs to supply you with a randomly generated list of new names and image urls. Don't be concerned with beautiful graphics and UI design. The focal point of this exercise is to demonstrate your abilities in starting a maintainable javascript code base that can handle updates to multiple parts of the page (i.e. title bar, column list and body) and has clean HTML/CSS structure. You may choose any JavaScript framework of your choice.

      .alert.alert-success
        %h2 Live Demo Site on Heroku
        %p= link_to "http://shielded-bayou-9558.herokuapp.com/", "http://shielded-bayou-9558.herokuapp.com/"


      .well
        %h3 Valerie's Description
        %p== My version of the exercise randomly pulls objects from the Ruby on Rails database in this case, cat objects. It can be expanded on with thumbnails and styling and whatnot. You can add more cats by going to #{link_to "the cats list", cats_path}, and entering more cats if you would like to try the serverside application. It is a traditional Ruby on Rails CRUD (create, read, update, delete) application and all of it is functional.


        %h3 Additions and Explanations
        %p Things I would do differently, if more people were using the applicaiton I would put more limits on the setTimeout functionality so they don't overwhelm the server. You can throttle it, or if you need more performance you can open a socket directly to the user. In this case, I went with polling the server instead. The home page is for the main page of the application. The cats repeat frequently because of the sample size. Using something like Flick API to post from is something I will look at doing in the future as an upgrade. Currently you can manually enter as many cats as you want to though.

        %h3 Other items
        %p The application needs internal tests, better styles, design and custom 404 pages. I also need to lock down application paths to the only endpoints I want users to have access to. Cross browser testing is soemthing that is needed as well, 
        though Twitter bootstrap does give me a bit of protection from that.

        %p== All source code is on #{link_to "github", "https://gitub.com/xianthe/ballin-octo-pix"}

        %h3 Tech Used
        %ul
          %li HTML5 
          %li CSS3
          %li Ruby on Rails 3.2
          %li jQuery
          %li Twitter Bootstrap
          %li Databases are sqlite3 in development and postgres in production
          %li Heroku for server hosting

:javascript

  //Initial timeout is 5s, can throttle this dynamically.
  var timeout = 5000;

  $(function(){

    //Make an initial request to the server
    setTimeout(updateItems, timeout);

  });

  function revealNewItems(){
    //Reveal all hidden items
    $('.hidden').show();

    //Remove the hidden class so items show up, and tag them all as new items;
    //remove new item tag from all old new items
    //$('.accordion').removeClass("new-items"); 
    $('.cats').removeClass("hidden");
    $('.accordion').removeClass("hidden");

    //Highlight the new items briefly
    $(".new-items").effect("highlight", {color: "#ffc8ba"}, 3000);
    $('.items').removeClass("new-items");

    $("#page h3").text("0 cats since you last viewed!");
  }

  function resetInterval(){
   if (timeout === 0)
   {
     //Alows the user to start the polling again
     timeout = 5000;
     $("#polling").text("Stop Polling");
     setTimeout(updateItems, timeout);

   }
   else
   {
      //Allows the user to stop the polling
      timeout = 0;
      $("#polling").text("Start Polling");
   }
  }

  function updateItems(){

    //Make an AJAX call to the rails server to get some data.
    $.getScript("/cats.js");
    var current_cats_count = parseInt($("#page h3").text().split(" ")[0],10);

    //If timeout is enabled, continue requesting data from the server.
    if (timeout !== 0){
     setTimeout(updateItems, timeout);
    }
  }

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => model_class.model_name.human